### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by comeredon** [nvandewalle/espp-tob-calculator#1]
love the app , works great indeed once you overcome the date thing. 
Maybe just a comment mentioning that the date cannot be weekend or bank holiday. 
otherwise good one 
Next step generate the document directly once the user input it s data and download it pre fill

**Comment by Nicwalle** [comment]
Thanks for the feedback, I updated the error message in the alert, will try to make it more pro-eminent. For real-life scenarios, should not be an issue as transactions will only take place on open days.

PDF generation is also on my TODO when I'll find time.

**Comment by Nicwalle** [comment]
@comeredon check this out (preview version): https://lively-tree-0917bc303-8.westeurope.5.azurestaticapps.net/ PDF is now generated automatically. If any feedback, please do it on this PR: #8
